### ISSUE TITLE
Create User (Donor and Recipient) Registration Form

### ISSUE THREAD

**Issue by IshitaBhatt-Dev** [Ishita-stpl/C2D#6]
- Create user registration form for donor and recipient both.
- Donor Registration Form Fields (Full Name, Date of Birth, Address, Province, Phone, Email, Username, Password)
- Recipient Registration Form Fields(Organization Name, Govt. Id number, Organization Registration Date, Address, Province, Contact Number, Email, Username, Password, Confirm Password)
- Update database with new entry.

**Comment by haocencol** [comment]
Attach a file with either a drawing or screen shot for this form.

**Comment by haocencol** [comment]
When you finish implementing a piece of code (i.e., functionality), it would be helpful if a screen recording is provided with the actual execution of the code.  That is, screen record the implemented functionality, upload to YouTube, and provide a private link as a Github comment for the issue in question.

**Comment by MJay27** [comment]
For completing this issue, We need to understand MVVM architecture and how to integrate MongoDB in it.
MVVM is useful to develop Xamrin app because, it cleanly separate the business and presentation logic of an application from its user interface (UI). Furthermore, through this unit testing is also possible.
References:
- https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/mvvm
- https://www.c-sharpcorner.com/article/xamarin-forms-create-mvvm-data-binding-application/

**Comment by haocencol** [comment]
Is this issue done yet?

**Comment by MJay27** [comment]
yes it is done.
